#!/usr/bin/env php
<?php

if (file_exists($autoload = __DIR__ . '/vendor/autoload.php')) {
    require $autoload;
} else {
    require dirname(__DIR__, 2) . '/autoload.php';
}

use Webteractive\Devstack\App;
use Webteractive\Devstack\Commands\Wp;
use Webteractive\Devstack\Commands\Php;
use Webteractive\Devstack\Commands\Init;
use Webteractive\Devstack\Commands\Redis;
use Webteractive\Devstack\Commands\MySql;
use Webteractive\Devstack\Commands\Shell;
use Webteractive\Devstack\Commands\Config;
use Webteractive\Devstack\Commands\Artisan;
use Webteractive\Devstack\Commands\Download;
use Webteractive\Devstack\Commands\Composer;
use Webteractive\Devstack\RegisterDockerComposeCommands;

$app = new App('Devstack', '1.1.7');

$app->add(new Init);
$app->add(new Config);
$app->add(new Download);
$app->add(new Artisan);
$app->add(new Php);
$app->add(new Composer);
$app->add(new Shell);
$app->add(new MySql);
$app->add(new Redis);
$app->add(new Wp);

RegisterDockerComposeCommands::register($app);

$app->run();