#!/usr/bin/env php
<?php

if (file_exists($autoload = __DIR__ . '/vendor/autoload.php')) {
    require $autoload;
} else {
    require dirname(__DIR__, 2) . '/autoload.php';
}

use Symfony\Component\Console\Application;
use Webteractive\Devstack\Commands\Config;
use Webteractive\Devstack\Commands\InitStack;
use Webteractive\Devstack\RegisterDockerCommands;
use Webteractive\Devstack\Commands\DownloadRuntimes;

$app = new Application;

$app->add(new InitStack);
$app->add(new Config);
$app->add(new DownloadRuntimes);

RegisterDockerCommands::register($app);

$app->run();